version: "3.7"

services:
  py-srv:
    build: py-srv
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: yandex/clickhouse-server
    healthcheck:
      test: pwd || exit 1
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s
    ports:
      - 8123
    volumes:
      - ./db:/etc/clickhouse-server